new file k6
nsl-test/platform-benchmarks pull request #4
Opened 2022-05-12 07:27 UTC by theboss21101999

2022-05-13 12:43 UTC, rverma-nsl requested changes

2022-05-13 12:43 UTC, rverma-nsl commented on approvals/success-script.js
> +        pm.expect(pm.response.json().message).to.eq("No active review process found for BET id 1125583457112");
again hardcoded, put it to environment variable

2022-05-17 06:36 UTC, theboss21101999 commented on approvals/success-script.js
> +      '{\n    "userName": "{{UserCCO}}",\n    "encryptedPassword": "J8JAIlEDnLvsHzljoQJ4VcWCdcVNJTYzWlc7yZaTRcH5roLNs6trxwD+Ax/XCy3UvJzxSDNLVaa2a7YVcVddeHC6oXuFMf0pNxYWTGi4Tl+ha36Y0DPd4VBFeqvRfDvB2Un
ya working on it

2022-05-17 06:36 UTC, theboss21101999 commented on approvals/success-script.js
> +        pm.expect(pm.response.json().message).to.eq("No active review process found for BET id 1125583457112");
ya working on it

2022-05-17 09:16 UTC, closed without merging